# Generated by Django 3.1.7 on 2021-03-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
